(* Example: Debug logging macro

   This demonstrates a practical use of the macro system for debugging.
   The debug macro prints an expression along with its value, similar to
   Rust's dbg! or Elixir's IO.inspect with label.

   Usage:
     let result = debug (compute_something x y)

   Expands to:
     let result =
       let __value = compute_something x y in
       Io.format "~s = ~p~n" ["compute_something x y"; __value];
       __value
*)

open Merlot_stdlib

(* Define the debug macro using Macro.defmacro.
   The stub function is auto-generated by the compiler.

   Macro.unquote splices the AST of a macro parameter into the quoted expression.
   Macro.to_string converts a macro parameter to its source text representation. *)
let debug = Macro.defmacro (fun expr ->
  Macro.quote (
    let __debug_value = Macro.unquote expr in
    let _ = Io.format "DEBUG: ~s = ~p~n" [Macro.to_string expr; __debug_value] in
    __debug_value
  )
)

(* Example functions *)
let add x y = x + y

let multiply x y = x * y

(* Main example showing debug macro in action *)
let example () =
  let a = 10 in
  let b = 20 in
  (* debug (add a b) prints: DEBUG: add(A, B) = 30 *)
  let sum = debug (add a b) in
  (* debug (a * 2) prints: DEBUG: (A * 2) = 20 *)
  let doubled = debug (a * 2) in
  (* debug (multiply sum doubled) prints: DEBUG: multiply(Sum, Doubled) = 600 *)
  let result = debug (multiply sum doubled) in
  result
